### ISSUE TITLE
添加一个优先级为5的配置源

### ISSUE THREAD

**Issue by xy-github-issue** [go-chassis/go-archaius#114]
目前 archaius 里的配置源，文件配置源优先级是最低的。
我觉得有一个比文件配置源优化级更低配置源是有必要的。
例如，我有这样的场景：go-chassis 的配置项太多了，并且有一些并非业务愿意关心的（如service-center的地址），我想为其中多数的配置项提供默认值，其他人使用大数时候直接使用默认值，感知不到这些配置项；但同时我也保留他自己去配置的能力，当他有需要的时候，他还是可以去了解、去(在文件中)配置出这些值。
目前对个场景我没有什么很好的办法，我可以在我的封装代码里设置对应配置项的环境变量，但是环境变量会覆盖文件，用户的配置能力就会被剥夺掉一些。
如果我有一个配置源，级别低于文件配置源，那我就可以通过它来实现这种设置默认值的工作。
实现路径最简单的就是，允许创建自定义级别的 Memory 配置源。

**Comment by tianxiaoliang** [comment]
现在有个CustomInit方法就是干这个事的

https://github.com/go-chassis/go-archaius/blob/e0b1b8fded15ad8bd92b88c6ab60d572e72bc677/archaius.go#L109
