### ISSUE TITLE
Archaius support file content as a value

### ISSUE THREAD

**Issue by tianxiaoliang** [go-chassis/go-archaius#21]
in real use case, user don't want to manage configs in a file separately. instead they want to use file content as a config value

**Comment by tianxiaoliang** [comment]
key is file name and value is file content.
if file content changed, fire event by key

**so source file should have different implements**

**Comment by tianxiaoliang** [comment]
so the API facing to user looks like

```go
func AddFileSource(path, priority init, o options)
```

**Comment by savitaashture** [comment]
API will be
func AddFile(file string, o ...options) error

AddFile("/path/to/file.yaml", archaius.WithHandleFunc(somefunc))
