### ISSUE TITLE
how to get config value from the local file?

### ISSUE THREAD

**Issue by fzxdev** [go-chassis/go-archaius#30]
I define a config file about database setting. follow example code in URL:
[https://go-chassis.readthedocs.io/en/latest/user-guides/dynamic-conf.html](https://go-chassis.readthedocs.io/en/latest/user-guides/dynamic-conf.html)
```golang
	func main() {
	    chassis.RegisterSchema("rest", &schemas.RestFulHello{})
	    chassis.RegisterSchema("rest", &schemas.RestFulMessage{})
	    //start all server you register in server/schemas.
	    if err := chassis.Init(); err != nil {
		lager.Logger.Error("Init failed.", err)
		return
	    }

	    //test code
	    dbCfgFile := fileutil.GetConfDir() + "\\db.yaml"
	    archaius.AddFile(dbCfgFile)
	    dbAddr:=archaius.GetString("dbconf.conn1.addr", "")
	    fmt.Println(dbAddr)

	    chassis.Run()
        }

```	
but I can't get value of dbAddr, it's empty.

Then I check code of [https://github.com/go-chassis/go-archaius/blob/master/examples/main.go](https://github.com/go-chassis/go-archaius/blob/master/examples/main.go), it's ok. 
but I find code
```golang
        ConfigFactory.DeInit() 
```
in sample code, and this code will clean all config item about FileSource. Is there any problem with this behavior?

Later, I just use object of NewYamlConfigurationSource to get config value, like this:
```golang
	//test
	dbCfgFile := fileutil.GetConfDir() + "\\db.yaml"
	fSource := filesource.NewYamlConfigurationSource()
	fSource.AddFileSource(dbCfgFile, 0)
	dbAddr, _:=fSource.GetConfigurationByKey("dbconf.conn1.addr")

	fmt.Println("---------------- DB Addr:", dbAddr)
```
It's work, and get real value of dbAddr.

**Comment by savitaashture** [comment]
@fzxdev 

For AddFile() function events were not handled properly.

```
            dbCfgFile := fileutil.GetConfDir() + "\\db.yaml"
	    archaius.AddFile(dbCfgFile)
	    dbAddr:=archaius.GetString("dbconf.conn1.addr", "")
	    fmt.Println(dbAddr)
```

Thats why above code was not giving proper output.

I have changed the logic and raised PR
https://github.com/go-chassis/go-archaius/pull/35

Once this is merged you can check again with latest code.

I have added testcase scenario in https://github.com/go-chassis/go-chassis/pull/388

Thanks for noticing this issue.

**Comment by savitaashture** [comment]
@fzxdev 

For AddFile() function events were not handled properly.

```
            dbCfgFile := fileutil.GetConfDir() + "\\db.yaml"
	    archaius.AddFile(dbCfgFile)
	    dbAddr:=archaius.GetString("dbconf.conn1.addr", "")
	    fmt.Println(dbAddr)
```

Thats why above code was not giving proper output.

I have changed the logic and raised PR
https://github.com/go-chassis/go-archaius/pull/35

Once this is merged you can check again with latest code.

I have added testcase scenario in https://github.com/go-chassis/go-chassis/pull/388

Thanks for noticing this issue.
