### ISSUE TITLE
examples/event示例：配置刷新失败

### ISSUE THREAD

**Issue by sundayslove** [go-chassis/go-archaius#63]
我想结合这个示例看一下Event部分的源码，但是示例跑的似乎有点问题：配置更改后，刷新失败。
运行环境：win10，IDE：Goland

操作：将配置文件中age的值由13改为132
日志如下：
2019/04/15 14:30:50 13
2019/04/15 14:30:55 13
2019/04/15 14:31:00 13
2019/04/15 14:31:01 DEBUG: file event [E:\microservice\go-archaius-0.14.0\examples\event\event.yaml RENAME], operation is %!d(MISSING). reload it.
2019/04/15 14:31:01 WARN: [[E:\microservice\go-archaius-0.14.0\examples\event\event.yaml open E:\microservice\go-archaius-0.14.0\examples\event\event.yaml: The system cannot find the file specified.]] file does not exist so not able to watch further
2019/04/15 14:31:01 DEBUG: file event [E:\microservice\go-archaius-0.14.0\examples\event\event.yaml___jb_old___ WRITE], operation is %!d(MISSING). reload it.
2019/04/15 14:31:01 DEBUG: Event generated events [[]]
2019/04/15 14:31:01 DEBUG: file event [E:\microservice\go-archaius-0.14.0\examples\event\event.yaml___jb_old___ REMOVE], operation is %!d(MISSING). reload it.
2019/04/15 14:31:01 WARN: the file change mode: ["E:\\microservice\\go-archaius-0.14.0\\examples\\event\\event.yaml___jb_old___": REMOVE], continue
2019/04/15 14:31:05 13
2019/04/15 14:31:10 13

**Comment by tianxiaoliang** [comment]
The system cannot find the file specified.]] file does not exist so not able to watch further

这个是问题

**Comment by sundayslove** [comment]
> The system cannot find the file specified.]] file does not exist so not able to watch further
> 
> 这个是问题

找到原因了。通过IDE自带终端的vi更改配置文件程序可以正常运行，如果直接在IDE里面更改配置文件就会报找不到文件，看样子是IDE对文件打开和修改做了点什么处理。。。
