### ISSUE TITLE
event可以监控配置中心的namespace吗？

### ISSUE THREAD

**Issue by sundayslove** [go-chassis/go-archaius#65]
https://github.com/go-chassis/go-archaius/blob/96fc4ada14924a9ce2f2ab0fc39c5e52e0cf0188/core/core.go#L68-L73

https://github.com/go-chassis/go-archaius/blob/96fc4ada14924a9ce2f2ab0fc39c5e52e0cf0188/core/config-manager/configurationmanager.go#L396

从这两处看event的key貌似就是配置信息的key。

event有办法做到监控整个文件吗？比如配置中心中有个namespace叫test，能注册针对这个test的event吗，而不仅仅是针对其中的某个键值对。

**Comment by sundayslove** [comment]
问题补充：go-archaius不支持apollo多namespace吗？

看Client结构体是初始化时就直接确定namespace的值了。
https://github.com/go-chassis/go-chassis-config/blob/41b5bee9c93bb0a0b349d20da1d2d581485fe430/apollo/apollo_client.go#L15-L23

**Comment by tianxiaoliang** [comment]
如果有兴趣可以贡献apollo部分的文档和源码，谢谢

**Comment by sundayslove** [comment]
好的
