### ISSUE TITLE
custom Event not work

### ISSUE THREAD

**Issue by hjdo** [go-chassis/go-archaius#72]
Hi, I Have a custom event listen for config file changes, but it not work, can you help me ?

```golang
package main

import (
	"fmt"
	"github.com/go-chassis/go-archaius"
	"github.com/go-chassis/go-archaius/core"
)
type Listener struct {
	Key string
}
func (e *Listener) Event(event *core.Event) {
	//  I want to dynamically get the latest values here.
	fmt.Printf("****************%v",event)
}
func main(){
	archaius.Init(archaius.WithRequiredFiles([]string{
		"./test.yaml",
	}))
	select{}
}
```

I want to get real-time changed values via `Event` function , but it didn't do anything, what do I need to do to make it work?

**Comment by tianxiaoliang** [comment]
you didn't register it. plz check example again

**Comment by hjdo** [comment]
I refer to [https://github.com/go-chassis/go-archaius/blob/master/examples/event/event.go](https://github.com/go-chassis/go-archaius/blob/master/examples/event/event.go) to achieve, How should I register it in this example?

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-archaius/blob/77d6ddbb22f9ca5c17c4b9bd4dddbf1a13081ee0/archaius.go#L266

**Comment by hjdo** [comment]
Thanks a lot for you, But why not add this `RegisterListener` to the `event` example?
