### ISSUE TITLE
UseFileNameAsKeyContentAsValue function import invalid in examples/file/ main.go 

### ISSUE THREAD

**Issue by gnodli** [go-chassis/go-archaius#78]
FileHandler has been moved to package utils from package filesource

**Comment by gnodli** [comment]
fix :
    add import github.com/go-chassis/go-archaius/sources/utils
    remove import github.com/go-chassis/go-archaius/sources/file-source
    modify line26 to err = archaius.AddFile("f3.yaml", archaius.WithFileHandler(utils.FileHandler(utils.UseFileNameAsKeyContentAsValue)))

**Comment by tianxiaoliang** [comment]
would you like to raise a pull request, thanks

**Comment by gnodli** [comment]
> would you like to raise a pull request, thanks

ok

**Comment by gnodli** [comment]
FileHandler link in README.md also invalid because same problem

**Comment by tianxiaoliang** [comment]
plz help us to correct the README, thanks
