### ISSUE TITLE
实现自定义配置中心的Client interface 参数疑问

### ISSUE THREAD

**Issue by Shonminh** [go-chassis/go-archaius#88]
## 文件名
source/remote/client.go

## 接口
```go
type Client interface {
	//PullConfigs pull all configs from remote
	PullConfigs(labels ...map[string]string) (map[string]interface{}, error)
	//PullConfig pull one config from remote
	PullConfig(key, contentType string, labels map[string]string) (interface{}, error)
	// PushConfigs push config to cc
	PushConfigs(data map[string]interface{}, labels map[string]string) (map[string]interface{}, error)
	// DeleteConfigsByKeys delete config for cc by keys
	DeleteConfigsByKeys(keys []string, labels map[string]string) (map[string]interface{}, error)
	//Watch get kv change results, you can compare them with local kv cache and refresh local cache
	Watch(f func(map[string]interface{}), errHandler func(err error), labels map[string]string) error
	Options() Options
}
```

## PullConfig
这个参数:contentType是什么意思

---

PS.目前我们的项目正在使用go-chassis来开发一个业务框架，已有的配置中心为apollo，正在做support apollo的工作，想问下目前为什么**停止**对apollo的开发了？

**Comment by tianxiaoliang** [comment]
停止apollo开发是由于我们开发了新的项目ServiceComb kie 配置服务
如果你想对接appollo可以实现source/apollo模块来对接，目前的remote+client层抽象的设计也是我的一种期望而已，你不一定非得去对接client，我认为不同的remote source还是有些特殊逻辑

**Comment by Shonminh** [comment]
> 停止apollo开发是由于我们开发了新的项目ServiceComb kie 配置服务
> 如果你想对接appollo可以实现source/apollo模块来对接，目前的remote+client层抽象的设计也是我的一种期望而已，你不一定非得去对接client，我认为不同的remote source还是有些特殊逻辑

谢谢，不过在master分支下并未发现source/apollo模块。

**Comment by tianxiaoliang** [comment]
是没有，你可以重新设计，重新实现，满足你的需求即可，贡献给我们我们也会非常欢迎

**Comment by tianxiaoliang** [comment]
后续go-chassis要接servicecomb kie，也是我大量投入人力的地方，感兴趣的话联系我 tianxiaoliang2017
